<?php
//Import PHPMailer classes into the global namespace
//These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require 'PHPMailer/src/Exception.php';
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';
//Load Composer's autoloader
require 'vendor/autoload.php';

$title  = isset($_POST['title']) ? $_POST['title'] : "";
$body  = isset($_POST['body']) ? $_POST['body'] : "";

try {
    $mail = new PHPMailer();
    
    $mail->CharSet = 'UTF-8';
    //Server settings
    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'Anhmetccb@gmail.com'; //paste one generated by Mailtrap
    $mail->Password = '123456789amt'; //paste one generated by Mailtrap
    $mail->SMTPSecure = 'tls';        //Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged
    $mail->Port       = 587;  

    
    // $mail->setFrom('Anhmetccb@gmail.com', 'Mailtrap');
    // $mail->addReplyTo('Anhmetccb@gmail.com', 'Mailtrap');
    // $mail->addAddress('Anhmetccb@gmail.com', 'Tim');


    // //Content
    // $mail->isHTML(true);                                  //Set email format to HTML
    // $mail->Subject = 'CẢNH BÁO HỆ THỐNG IoT CHO CÂY SA NHÂN TẠI VƯỜN ƯƠM TRƯỜNG ĐẠI HỌC NHA TRANG';
    // $mail->Body    = "$title $body";
    // $mail->AltBody = '';

    // $mail->send();
    // echo 'Message has been sent';
     //Recipients
     $mail->setFrom('Anhmetccb@gmail.com', 'Mailer');
     $mail->addAddress('thanhtuyennguyenmta@gmail.com', 'Tuyen');     //Add a recipient
     // $mail->addAddress('ellen@example.com');               //Name is optional
     // $mail->addReplyTo('info@example.com', 'Information');
     // $mail->addCC('cc@example.com');
     // $mail->addBCC('bcc@example.com');
 
     //Attachments
     // $mail->addAttachment('/var/tmp/file.tar.gz');         //Add attachments
     // $mail->addAttachment('/tmp/image.jpg', 'new.jpg');    //Optional name
 
     //Content
     $body = "$title $body" ;
     
     $mail->isHTML(true);                                  //Set email format to HTML
     $mail->Subject = 'CẢNH BÁO HỆ THỐNG IoT VỀ ĐIỀU KIỆN SINH TRƯỞNG CỦA CÂY SA NHÂN TẠI VƯỜN ƯƠM ĐẠI HỌC NHA TRANG ';
     $mail->Body    = $body ;
     $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
 
     $mail->send();
     echo $body;
     echo 'Message has been sent';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}

?>