//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dataQLKSEntities : DbContext
    {
        public dataQLKSEntities()
            : base("name=dataQLKSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblChucVu> tblChucVus { get; set; }
        public virtual DbSet<tblDichVu> tblDichVus { get; set; }
        public virtual DbSet<tblDichVuDaDat> tblDichVuDaDats { get; set; }
        public virtual DbSet<tblHoaDon> tblHoaDons { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public virtual DbSet<tblLoaiPhong> tblLoaiPhongs { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblPhieuDatPhong> tblPhieuDatPhongs { get; set; }
        public virtual DbSet<tblPhong> tblPhongs { get; set; }
        public virtual DbSet<tblTang> tblTangs { get; set; }
        public virtual DbSet<tblTinhTrangHoaDon> tblTinhTrangHoaDons { get; set; }
        public virtual DbSet<tblTinhTrangPhieuDatPhong> tblTinhTrangPhieuDatPhongs { get; set; }
        public virtual DbSet<tblTinhTrangPhong> tblTinhTrangPhongs { get; set; }
        public virtual DbSet<tblTinNhan> tblTinNhans { get; set; }
    }
}
