//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHoaDon()
        {
            this.tblDichVuDaDats = new HashSet<tblDichVuDaDat>();
        }
    
        public int ma_hd { get; set; }
        public Nullable<int> ma_nv { get; set; }
        public Nullable<int> ma_pdp { get; set; }
        public Nullable<System.DateTime> ngay_tra_phong { get; set; }
        public Nullable<int> ma_tinh_trang { get; set; }
        public Nullable<double> tien_phong { get; set; }
        public Nullable<double> tien_dich_vu { get; set; }
        public Nullable<double> phu_thu { get; set; }
        public Nullable<double> tong_tien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDichVuDaDat> tblDichVuDaDats { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblPhieuDatPhong tblPhieuDatPhong { get; set; }
        public virtual tblTinhTrangHoaDon tblTinhTrangHoaDon { get; set; }
    }
}
